FROM node:18.17.0 as builder

WORKDIR /app/admin

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . .

RUN rm -rf node_modules

RUN apt-get update

RUN yarn install

RUN yarn build:admin

FROM nginx

EXPOSE 80 

#COPY nginx/nginx.conf /etc/nginx/nginx.conf

# /app is the default path for medusa-admin
#COPY --from=builder /app/admin/build /usr/share/nginx/html/admin 
COPY --from=builder /app/admin/build /usr/share/nginx/html 

ENTRYPOINT ["nginx", "-g", "daemon off;"]